<?php

namespace Container7Qkm6lY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LyvQynAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LyvQynA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LyvQynA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CommandeController::ajouterproduit' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CommandeController::deleteproduit' => ['privates', '.service_locator.WiddWt1', 'get_ServiceLocator_WiddWt1Service', true],
            'App\\Controller\\CommandeController::editproduitForm' => ['privates', '.service_locator.WiddWt1', 'get_ServiceLocator_WiddWt1Service', true],
            'App\\Controller\\CommandeController::show1' => ['privates', '.service_locator.RXaRRrV', 'get_ServiceLocator_RXaRRrVService', true],
            'App\\Controller\\ProduitController::ajouterproduit' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProduitController::deleteproduit' => ['privates', '.service_locator.LrkmB3h', 'get_ServiceLocator_LrkmB3hService', true],
            'App\\Controller\\ProduitController::detailsProduit' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController::editproduitForm' => ['privates', '.service_locator.LrkmB3h', 'get_ServiceLocator_LrkmB3hService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController::show1' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController::show2' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CommandeController:ajouterproduit' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CommandeController:deleteproduit' => ['privates', '.service_locator.WiddWt1', 'get_ServiceLocator_WiddWt1Service', true],
            'App\\Controller\\CommandeController:editproduitForm' => ['privates', '.service_locator.WiddWt1', 'get_ServiceLocator_WiddWt1Service', true],
            'App\\Controller\\CommandeController:show1' => ['privates', '.service_locator.RXaRRrV', 'get_ServiceLocator_RXaRRrVService', true],
            'App\\Controller\\ProduitController:ajouterproduit' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProduitController:deleteproduit' => ['privates', '.service_locator.LrkmB3h', 'get_ServiceLocator_LrkmB3hService', true],
            'App\\Controller\\ProduitController:detailsProduit' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController:editproduitForm' => ['privates', '.service_locator.LrkmB3h', 'get_ServiceLocator_LrkmB3hService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController:show1' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ProduitController:show2' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CommandeController::ajouterproduit' => '?',
            'App\\Controller\\CommandeController::deleteproduit' => '?',
            'App\\Controller\\CommandeController::editproduitForm' => '?',
            'App\\Controller\\CommandeController::show1' => '?',
            'App\\Controller\\ProduitController::ajouterproduit' => '?',
            'App\\Controller\\ProduitController::deleteproduit' => '?',
            'App\\Controller\\ProduitController::detailsProduit' => '?',
            'App\\Controller\\ProduitController::editproduitForm' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Controller\\ProduitController::show1' => '?',
            'App\\Controller\\ProduitController::show2' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CommandeController:ajouterproduit' => '?',
            'App\\Controller\\CommandeController:deleteproduit' => '?',
            'App\\Controller\\CommandeController:editproduitForm' => '?',
            'App\\Controller\\CommandeController:show1' => '?',
            'App\\Controller\\ProduitController:ajouterproduit' => '?',
            'App\\Controller\\ProduitController:deleteproduit' => '?',
            'App\\Controller\\ProduitController:detailsProduit' => '?',
            'App\\Controller\\ProduitController:editproduitForm' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'App\\Controller\\ProduitController:show1' => '?',
            'App\\Controller\\ProduitController:show2' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
