services:
    # Déclaration du service session
    Symfony\Component\HttpFoundation\Session\SessionInterface: '@session'
    Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler: null

    session:
        class: Symfony\Component\HttpFoundation\Session\Session
        arguments:
            - '@session.storage'
            - '@session.attribute_bag'
            - '@session.flash_bag'
        public: true

    session.storage:
        class: Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage
        arguments:
            - '%session.storage.options%'
        public: true

    session.attribute_bag:
        class: Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag
        public: true

    session.flash_bag:
        class: Symfony\Component\HttpFoundation\Session\Flash\FlashBag
        public: true

    App\Services\PanierServices:
        arguments:
            $session: '@session'
            $repoproduit: '@App\Repository\ProduitRepository'

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

# makes classes in src/ available to be used as services
# this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
