<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLR0ZusX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLR0ZusX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLR0ZusX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLR0ZusX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLR0ZusX\App_KernelDevDebugContainer([
    'container.build_hash' => 'LR0ZusX',
    'container.build_id' => '2170c55b',
    'container.build_time' => 1709835117,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLR0ZusX');
