<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH6XZ5lq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH6XZ5lq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH6XZ5lq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH6XZ5lq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH6XZ5lq\App_KernelDevDebugContainer([
    'container.build_hash' => 'H6XZ5lq',
    'container.build_id' => '87362086',
    'container.build_time' => 1709287643,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH6XZ5lq');
